spring.application.name=JPAPRACTICE

spring.datasource.url=jdbc:mysql://localhost:3306/Students?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nikhil@9897

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

debug=true